# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-25 16:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_post_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='image',
            new_name='image1',
        ),
    ]
