# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-25 23:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20180225_1834'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='icerik',
        ),
        migrations.AddField(
            model_name='post',
            name='img1',
            field=models.ImageField(blank=True, upload_to='', verbose_name='İmg 1'),
        ),
        migrations.AddField(
            model_name='post',
            name='img2',
            field=models.ImageField(blank=True, upload_to='', verbose_name='İmg 2'),
        ),
        migrations.AddField(
            model_name='post',
            name='img3',
            field=models.ImageField(blank=True, upload_to='', verbose_name='İmg 3'),
        ),
        migrations.AddField(
            model_name='post',
            name='interested_1',
            field=models.TextField(blank=True, max_length=500, verbose_name='İlgi Alanlarım 1'),
        ),
        migrations.AddField(
            model_name='post',
            name='interested_2',
            field=models.TextField(blank=True, max_length=500, verbose_name='İlgi Alanlarım 2'),
        ),
        migrations.AddField(
            model_name='post',
            name='interested_3',
            field=models.TextField(blank=True, max_length=500, verbose_name='İlgi Alanlarım 3'),
        ),
        migrations.AddField(
            model_name='post',
            name='what_to_do',
            field=models.TextField(blank=True, max_length=500, verbose_name='Ne Yaparım ?'),
        ),
        migrations.AddField(
            model_name='post',
            name='who',
            field=models.TextField(blank=True, max_length=500, verbose_name='Hakkmmda'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Profil'),
        ),
    ]
