# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-26 00:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20180226_0159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='interested_1',
            field=models.TextField(blank=True, default='İlgi Alanı', max_length=500, verbose_name='İlgi Alanlarım 1'),
        ),
        migrations.AlterField(
            model_name='post',
            name='interested_2',
            field=models.TextField(blank=True, default='İlgi Alanı', max_length=500, verbose_name='İlgi Alanlarım 2'),
        ),
        migrations.AlterField(
            model_name='post',
            name='interested_3',
            field=models.TextField(blank=True, default='İlgi Alanı', max_length=500, verbose_name='İlgi Alanlarım 3'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(default='Başlık', max_length=123, verbose_name='Ad'),
        ),
        migrations.AlterField(
            model_name='post',
            name='what_to_do',
            field=models.TextField(blank=True, default='Ne yapar', max_length=500, verbose_name='Ne Yaparım ?'),
        ),
        migrations.AlterField(
            model_name='post',
            name='who',
            field=models.TextField(blank=True, default='Kim', max_length=500, verbose_name='Hakkımda'),
        ),
    ]
